name: example-python-controller
author: change-me
source: https://github.com/VU-ASE/service-template-python
version: 0.0.1
description: A template service in Python

# While the name is "example-python-controller", the default actuator is setup 
# to look for an output called decision from the "controller" service. Since it's
# rather tedious to change the service.yaml of the actuator input from "controller"
# to "example-python-controller" we can instead use the 'as: controller' which
# lets us pretend to be a service with the name "controller".
as: controller

commands:
  build: echo "no build command needed"
  run: ./src/main.py
  
inputs:
  - service: imaging
    streams:
      - path

outputs:
  - decision

configuration:
  - name: number-example
    type: number
    value: 30
  - name: string-example
    type: string
    value: "hello all"
  - name: tunable-string-example
    type: string
    value: "hello all, this is tunable"
    tunable: true
