name: SERVICE_NAME
author: SERVICE_AUTHOR
source: SERVICE_SOURCE
version: SERVICE_VERSION
description: A template service in Python

commands:
  build: make build
  run: make start

inputs:
  - service: example-input
    streams:
      - rpm-data
outputs:
  - example-output

configuration:
  - name: number-example
    type: number
    value: 30
  - name: string-example
    type: string
    value: "hello all"
  - name: tunable-string-example
    type: string
    value: "hello all, this is tunable"
    tunable: true